server:
    dockerfile: $PWD/docker/server/Dockerfile
    build: $PWD/docker/server
    links:
        - mysql
        - memcached
    ports:
        - "80:80"
        - "3000:3000"
    volumes:
        - $PWD:/var/www/html/docker
    environment:
        - PROJECT_HOST_ENV=docker.dev

mysql:
    dockerfile: $PWD/docker/db/Dockerfile
    build: $PWD/docker/db
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=lecaoquochung
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
    volumes:
        - $PWD/docker/db/init.d:/docker-entrypoint-initdb.d
        - $PWD/app/Config/Schema:/schema
    mem_limit: 1000000000

memcached:
  image: memcached
